config/routes.rb
Rails.application.routes.draw do

  root 'pokemons#index'
  resources :pokemons

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end

  def show

    @pokemon = Pokemon.find(params[:id])

    respond_to do |format|
      format.json { render json: @pokemon }
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokedex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.js' %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pokemons/index.html.erb
<div id="pokebox">

</div>

<div id="pokebox2">

</div>

<%= @pokemons.each do |x| %>
  <li class="pokelist"><a class="pokelink" href="<%= pokemon_path(x) %>"><%= x.name %></a> : <a class="pokelink2" href="<%= pokemon_path(x) %>">Full details</a></li>
<% end %>





<script id="entry-template" type="text/x-handlebars-template">
  <img src="{{image_url}}" />
  <p>{{name}}</p>
</script>

<script id="entry-template2" type="text/x-handlebars-template">
  <img src="{{image_url}}" />
  <p>{{name}}</p>
  <p>{{attack}}</p>
  <p>{{defense}}</p>
  <p>{{happiness}}</p>
  <p>{{speed}}</p>
  <p>{{species}}</p>
  <p>{{growth_rate}}</p>
</script>

app/views/pokemons/show.html.erb
<script id="entry-template2" type="text/x-handlebars-template">
  <img src="{{image_url}}" />
  <p>{{name}}</p>
  <p>{{attack}}</p>
  <p>{{defense}}</p>
  <p>{{happiness}}</p>
  <p>{{speed}}</p>
  <p>{{species}}</p>
  <p>{{growth_rate}}</p>
</script>